name: 'Run Renovate'
description: 'Runs Renovate against the current repo'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v7
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v46.2.5
      env:
        RENOVATE_TOKEN: ${{ github.token }}
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        LOG_LEVEL: debug
        NODE_OPTIONS: "--max-old-space-size=4096"
      with:
        configurationFile: ${{ github.action_path }}/renovate-global.json
