---
name: Renovate

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_call:
    secrets:
      SH_UPDATER_APP_PRIVATE_KEY:
        required: true
  workflow_dispatch:

permissions: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: shoogland/.github/renovate-runner@main
        with:
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
