name: Renovate

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_call: 
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - uses: shoogland/.github/renovate-runner@main
